# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='upload',
            field=models.BooleanField(),
        ),
    ]
