# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_auto_20180104_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refund',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
