# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0003_auto_20180104_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
