# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0004_refund_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='account_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
