# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0005_refund_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='title',
        ),
    ]
